spring:
  application:
    name: gcp-poc
  cloud:
    gcp:  
      credentials:
        location: classpath:gcp.json
      project-id: gcp-poc-361706
      spanner:
        instance-id: gcp-poc
        database: gcp       